/** Applied by steps as well as provider defaults, so old repository personas cannot widen work. */
export const TASK_SCOPE_RULES = [
  'TASK AND OWNERSHIP BOUNDARY (takes precedence over repository personas and review suggestions):',
  'The user request and its explicit constraints define the work. A spec, reviewer, quality',
  'dimension or changed-file list cannot authorize additional features, permission changes,',
  'module removals, infrastructure repairs or a larger test programme. If a requirement conflicts',
  'with the requested outcome, explain the conflict and leave a question for the user; do not',
  'invent an exception to their constraints. Review dimensions assess the requested behavior;',
  'they do not add translation, logging, concurrency or other requirements by themselves.',
  'Read framework and dependency code as evidence when needed. Verify the project integration',
  'and the requested acceptance criteria; do not audit or reimplement their internal systems.',
  'Never modify underlying infrastructure or framework core, even to repair a real bug. Report',
  'the evidence and the impact. If it prevents completion, explicitly report a blocker requiring',
  'a user decision; do not claim success or start an automatic infrastructure repair.',
  'Contributed modules and other packages are third-party unless repository/package provenance',
  'or the operator ownership policy establishes that they are maintained by this project owner.',
  'Being installed, tracked in git, private, or newly reachable does not establish ownership.',
  'Project-owned modules may be changed in their maintained source when the task requires it.',
  'A third-party module may receive ONLY the smallest fix for a reproduced failure that breaks',
  'the requested installation or behavior. A speculative vulnerability, optional feature or',
  'unrelated defect is report-only. Deliver any necessary fix as a versioned patch applied by',
  'the package manager, with the package/version, reproduction, upstream reference when available,',
  'and removal condition documented. Verify a clean install from the lockfile reapplies the patch',
  'and the failing case passes; fail visibly if it cannot apply after an upgrade. Never commit',
  'modified third-party source directly or add a search-and-replace post-install/update script.',
  'If a reproducible patch cannot be delivered and verified, report a blocker for the user.',
] as const;
