import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { FormSchema } from '@haive/shared';
import type { StepContext, StepDefinition } from '../../step-definition.js';
import { pathExists } from './_helpers.js';

export interface SkillCheck {
  skillId: string;
  skillPath: string;
  passed: boolean;
  issues: string[];
}

export interface SkillVerificationDetect {
  checks: SkillCheck[];
  missingFileIds: string[];
  brokenStructureIds: string[];
}

export interface SkillVerificationApply {
  checks: SkillCheck[];
  regenerated: string[];
  passed: boolean;
}

interface ParsedSkill {
  name: string | null;
  description: string | null;
  hasTitle: boolean;
  hasDescriptionSection: boolean;
  hasInstructionsSection: boolean;
}

const FRONTMATTER_RE = /^---\n([\s\S]*?)\n---/;

function parseSkillMarkdown(text: string): ParsedSkill {
  const fm = text.match(FRONTMATTER_RE);
  let name: string | null = null;
  let description: string | null = null;
  if (fm && fm[1]) {
    const nameMatch = fm[1].match(/^name:\s*(.+)$/m);
    if (nameMatch && nameMatch[1]) name = nameMatch[1].trim();
    const descMatch = fm[1].match(/^description:\s*(.+)$/m);
    if (descMatch && descMatch[1]) description = descMatch[1].trim();
  }
  return {
    name,
    description,
    hasTitle: /^#\s+\S/m.test(text),
    hasDescriptionSection: /^##\s+Description\b/m.test(text),
    hasInstructionsSection: /^##\s+Instructions\b/m.test(text),
  };
}

function stubSkillContent(skillId: string): string {
  const fm = [
    '---',
    `name: ${skillId}`,
    `description: ${skillId} (stub regenerated by skill-verification; fill in before use)`,
    '---',
    '',
  ].join('\n');
  const body = [
    `# ${skillId}`,
    '',
    '## Description',
    '',
    `${skillId} stub regenerated because the original SKILL.md file was missing. Replace this section with a real description.`,
    '',
    '## Instructions',
    '',
    'Skill instructions missing. Re-run step 09_5 skill generation to produce a full entry, or replace this section manually.',
    '',
  ].join('\n');
  return fm + body;
}

async function listSkillDirs(repo: string): Promise<string[]> {
  const root = path.join(repo, '.claude', 'skills');
  if (!(await pathExists(root))) return [];
  try {
    const entries = await readdir(root, { withFileTypes: true });
    return entries
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
      .sort();
  } catch {
    return [];
  }
}

async function checkSkill(repo: string, skillId: string): Promise<SkillCheck> {
  const skillPath = path.join(repo, '.claude', 'skills', skillId, 'SKILL.md');
  const issues: string[] = [];
  if (!(await pathExists(skillPath))) {
    return {
      skillId,
      skillPath,
      passed: false,
      issues: ['SKILL.md missing'],
    };
  }
  let text: string;
  try {
    text = await readFile(skillPath, 'utf8');
  } catch (err) {
    return {
      skillId,
      skillPath,
      passed: false,
      issues: [`read failed: ${(err as Error).message}`],
    };
  }
  if (text.trim().length === 0) {
    return {
      skillId,
      skillPath,
      passed: false,
      issues: ['SKILL.md empty'],
    };
  }
  const parsed = parseSkillMarkdown(text);
  if (!parsed.name) issues.push('frontmatter missing name');
  if (!parsed.description) issues.push('frontmatter missing description');
  if (!parsed.hasTitle) issues.push('missing level-1 title heading');
  if (!parsed.hasDescriptionSection) issues.push('missing ## Description section');
  if (!parsed.hasInstructionsSection) issues.push('missing ## Instructions section');
  return {
    skillId,
    skillPath,
    passed: issues.length === 0,
    issues,
  };
}

export const skillVerificationStep: StepDefinition<
  SkillVerificationDetect,
  SkillVerificationApply
> = {
  metadata: {
    id: '09_6-skill-verification',
    workflowType: 'onboarding',
    index: 12,
    title: 'Skill verification',
    description:
      'Walks .claude/skills/, verifies each SKILL.md has the expected frontmatter and section structure, and regenerates stub files for skills whose SKILL.md went missing.',
    requiresCli: false,
  },

  async detect(ctx: StepContext): Promise<SkillVerificationDetect> {
    const skillIds = await listSkillDirs(ctx.repoPath);
    const checks = await Promise.all(skillIds.map((id) => checkSkill(ctx.repoPath, id)));
    const missingFileIds = checks
      .filter((c) => c.issues.includes('SKILL.md missing'))
      .map((c) => c.skillId);
    const brokenStructureIds = checks
      .filter((c) => !c.passed && !c.issues.includes('SKILL.md missing'))
      .map((c) => c.skillId);
    ctx.logger.info(
      {
        total: checks.length,
        passed: checks.filter((c) => c.passed).length,
        missing: missingFileIds.length,
        broken: brokenStructureIds.length,
      },
      'skill verification detect complete',
    );
    return { checks, missingFileIds, brokenStructureIds };
  },

  form(_ctx, detected): FormSchema | null {
    if (detected.missingFileIds.length === 0) {
      return null;
    }
    return {
      title: 'Regenerate missing skills',
      description: `${detected.missingFileIds.length} SKILL.md file(s) are missing. Unchecking "regenerateMissing" leaves them as failures.`,
      fields: [
        {
          type: 'checkbox',
          id: 'regenerateMissing',
          label: 'Regenerate missing SKILL.md files as stubs',
          default: true,
        },
      ],
      submitLabel: 'Continue',
    };
  },

  async apply(ctx, args): Promise<SkillVerificationApply> {
    const detected = args.detected as SkillVerificationDetect;
    const values = args.formValues as { regenerateMissing?: boolean };
    const shouldRegenerate = values.regenerateMissing !== false;
    const regenerated: string[] = [];

    if (shouldRegenerate) {
      for (const skillId of detected.missingFileIds) {
        const skillPath = path.join(ctx.repoPath, '.claude', 'skills', skillId, 'SKILL.md');
        await writeFile(skillPath, stubSkillContent(skillId), 'utf8');
        regenerated.push(skillId);
      }
    }

    const finalChecks = shouldRegenerate
      ? await Promise.all(
          detected.checks.map((c) =>
            detected.missingFileIds.includes(c.skillId)
              ? checkSkill(ctx.repoPath, c.skillId)
              : Promise.resolve(c),
          ),
        )
      : detected.checks;

    const passed = finalChecks.every((c) => c.passed);
    ctx.logger.info(
      {
        regenerated: regenerated.length,
        passed,
        brokenStructure: detected.brokenStructureIds.length,
      },
      'skill verification apply complete',
    );
    return { checks: finalChecks, regenerated, passed };
  },
};
