import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { eq } from 'drizzle-orm';
import { schema } from '@haive/database';
import type { CliProviderName, FormSchema } from '@haive/shared';
import { getCliProviderMetadata } from '@haive/shared';
import type { StepContext, StepDefinition } from '../../step-definition.js';
import { pathExists } from './_helpers.js';

const DEFAULT_PROJECT_SKILLS_DIR = '.claude/skills';

async function resolveProjectSkillsDir(ctx: StepContext): Promise<string> {
  if (!ctx.cliProviderId) return DEFAULT_PROJECT_SKILLS_DIR;
  const row = await ctx.db.query.cliProviders.findFirst({
    where: eq(schema.cliProviders.id, ctx.cliProviderId),
    columns: { name: true },
  });
  if (!row) return DEFAULT_PROJECT_SKILLS_DIR;
  return getCliProviderMetadata(row.name as CliProviderName).projectSkillsDir;
}

function skillsDirParts(skillsDir: string): string[] {
  return skillsDir.split('/').filter((p) => p.length > 0);
}

export interface SkillCheck {
  skillId: string;
  skillPath: string;
  passed: boolean;
  issues: string[];
}

export interface SkillVerificationDetect {
  checks: SkillCheck[];
  missingFileIds: string[];
  brokenStructureIds: string[];
  /** Repo-relative skills dir resolved from the active CLI's catalog entry. */
  projectSkillsDir: string;
}

export interface SkillVerificationApply {
  checks: SkillCheck[];
  regenerated: string[];
  passed: boolean;
}

interface ParsedSkill {
  name: string | null;
  description: string | null;
  hasTitle: boolean;
  hasOverviewSection: boolean;
}

const FRONTMATTER_RE = /^---\n([\s\S]*?)\n---/;
const FOLDED_DESC_RE = /^description:\s*>\s*\n([\s\S]*?)(?=\n[A-Za-z][^\n]*:|\n*$)/m;

function parseSkillMarkdown(text: string): ParsedSkill {
  const fm = text.match(FRONTMATTER_RE);
  let name: string | null = null;
  let description: string | null = null;
  if (fm && fm[1]) {
    const fmBody = fm[1];
    const nameMatch = fmBody.match(/^name:\s*(.+)$/m);
    if (nameMatch && nameMatch[1]) name = nameMatch[1].trim();
    const inlineDesc = fmBody.match(/^description:\s*(\S.*)$/m);
    if (inlineDesc && inlineDesc[1]) {
      description = inlineDesc[1].trim();
    } else {
      const folded = fmBody.match(FOLDED_DESC_RE);
      if (folded && folded[1]) {
        const lines = folded[1]
          .split('\n')
          .map((l) => l.replace(/^\s+/, ''))
          .filter((l) => l.length > 0);
        if (lines.length > 0) description = lines.join(' ');
      }
    }
  }
  return {
    name,
    description,
    hasTitle: /^#\s+\S/m.test(text),
    hasOverviewSection: /^##\s+Overview\b/m.test(text),
  };
}

function stubSkillContent(skillId: string): string {
  const fm = [
    '---',
    `name: ${skillId}`,
    `description: ${skillId} (stub regenerated by skill-verification; fill in before use)`,
    '---',
    '',
  ].join('\n');
  const body = [
    `# ${skillId}`,
    '',
    '## Overview',
    '',
    `${skillId} stub regenerated because the original SKILL.md file was missing. Re-run step 09_5 skill generation to produce a full entry, or replace this section manually.`,
    '',
  ].join('\n');
  return fm + body;
}

async function listSkillDirs(repo: string, skillsDir: string): Promise<string[]> {
  const root = path.join(repo, ...skillsDirParts(skillsDir));
  if (!(await pathExists(root))) return [];
  try {
    const entries = await readdir(root, { withFileTypes: true });
    return entries
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
      .sort();
  } catch {
    return [];
  }
}

async function checkSkill(repo: string, skillsDir: string, skillId: string): Promise<SkillCheck> {
  const skillPath = path.join(repo, ...skillsDirParts(skillsDir), skillId, 'SKILL.md');
  const issues: string[] = [];
  if (!(await pathExists(skillPath))) {
    return {
      skillId,
      skillPath,
      passed: false,
      issues: ['SKILL.md missing'],
    };
  }
  let text: string;
  try {
    text = await readFile(skillPath, 'utf8');
  } catch (err) {
    return {
      skillId,
      skillPath,
      passed: false,
      issues: [`read failed: ${(err as Error).message}`],
    };
  }
  if (text.trim().length === 0) {
    return {
      skillId,
      skillPath,
      passed: false,
      issues: ['SKILL.md empty'],
    };
  }
  const parsed = parseSkillMarkdown(text);
  if (!parsed.name) issues.push('frontmatter missing name');
  if (!parsed.description) issues.push('frontmatter missing description');
  if (!parsed.hasTitle) issues.push('missing level-1 title heading');
  if (!parsed.hasOverviewSection) issues.push('missing ## Overview section');
  return {
    skillId,
    skillPath,
    passed: issues.length === 0,
    issues,
  };
}

export const skillVerificationStep: StepDefinition<
  SkillVerificationDetect,
  SkillVerificationApply
> = {
  metadata: {
    id: '09_6-skill-verification',
    workflowType: 'onboarding',
    index: 12,
    title: 'Skill verification',
    description:
      'Walks the active CLI’s project skills directory, verifies each SKILL.md has the expected frontmatter and section structure, and regenerates stub files for skills whose SKILL.md went missing.',
    requiresCli: true,
  },

  async detect(ctx: StepContext): Promise<SkillVerificationDetect> {
    const projectSkillsDir = await resolveProjectSkillsDir(ctx);
    const skillIds = await listSkillDirs(ctx.repoPath, projectSkillsDir);
    const checks = await Promise.all(
      skillIds.map((id) => checkSkill(ctx.repoPath, projectSkillsDir, id)),
    );
    const missingFileIds = checks
      .filter((c) => c.issues.includes('SKILL.md missing'))
      .map((c) => c.skillId);
    const brokenStructureIds = checks
      .filter((c) => !c.passed && !c.issues.includes('SKILL.md missing'))
      .map((c) => c.skillId);
    ctx.logger.info(
      {
        total: checks.length,
        passed: checks.filter((c) => c.passed).length,
        missing: missingFileIds.length,
        broken: brokenStructureIds.length,
        projectSkillsDir,
      },
      'skill verification detect complete',
    );
    return { checks, missingFileIds, brokenStructureIds, projectSkillsDir };
  },

  form(_ctx, detected): FormSchema | null {
    if (detected.missingFileIds.length === 0) {
      return null;
    }
    return {
      title: 'Regenerate missing skills',
      description: `${detected.missingFileIds.length} SKILL.md file(s) are missing. Unchecking "regenerateMissing" leaves them as failures.`,
      fields: [
        {
          type: 'checkbox',
          id: 'regenerateMissing',
          label: 'Regenerate missing SKILL.md files as stubs',
          default: true,
        },
      ],
      submitLabel: 'Continue',
    };
  },

  async apply(ctx, args): Promise<SkillVerificationApply> {
    const detected = args.detected as SkillVerificationDetect;
    const values = args.formValues as { regenerateMissing?: boolean };
    const shouldRegenerate = values.regenerateMissing !== false;
    const regenerated: string[] = [];
    const skillsDir = detected.projectSkillsDir ?? DEFAULT_PROJECT_SKILLS_DIR;

    if (shouldRegenerate) {
      for (const skillId of detected.missingFileIds) {
        const skillPath = path.join(
          ctx.repoPath,
          ...skillsDirParts(skillsDir),
          skillId,
          'SKILL.md',
        );
        await writeFile(skillPath, stubSkillContent(skillId), 'utf8');
        regenerated.push(skillId);
      }
    }

    const finalChecks = shouldRegenerate
      ? await Promise.all(
          detected.checks.map((c) =>
            detected.missingFileIds.includes(c.skillId)
              ? checkSkill(ctx.repoPath, skillsDir, c.skillId)
              : Promise.resolve(c),
          ),
        )
      : detected.checks;

    const passed = finalChecks.every((c) => c.passed);
    ctx.logger.info(
      {
        regenerated: regenerated.length,
        passed,
        brokenStructure: detected.brokenStructureIds.length,
      },
      'skill verification apply complete',
    );
    return { checks: finalChecks, regenerated, passed };
  },
};
