import { describe, expect, it } from 'vitest';
import type { AgentSpec } from '../src/step-engine/steps/onboarding/_agent-templates.js';
import { agentsIndexMarkdown } from '../src/step-engine/steps/onboarding/07-generate-files.js';

function spec(id: string, description: string): AgentSpec {
  return {
    id,
    title: id,
    description,
    color: 'purple',
    field: 'quality',
    tools: ['Read'],
    coreMission: 'm',
    responsibilities: ['r'],
    whenInvoked: ['w'],
    executionSteps: [{ title: 'T', body: 'B' }],
    outputFormat: '```',
    qualityCriteria: ['q'],
    antiPatterns: ['a'],
  };
}

describe('agentsIndexMarkdown', () => {
  it('renders an Auto-generated header and a markdown table sorted alphabetically', () => {
    const md = agentsIndexMarkdown([spec('zeta', 'Zeta agent.'), spec('alpha', 'Alpha agent.')]);
    expect(md).toMatch(/^# Agents Index/);
    expect(md).toContain('Auto-generated by Haive onboarding');
    expect(md).toContain('| Agent | Description |');
    const alphaIdx = md.indexOf('alpha');
    const zetaIdx = md.indexOf('zeta');
    expect(alphaIdx).toBeGreaterThan(0);
    expect(zetaIdx).toBeGreaterThan(alphaIdx);
  });

  it('links each row at the relative agent file path', () => {
    const md = agentsIndexMarkdown([spec('alpha', 'Alpha agent.')]);
    expect(md).toContain('| [alpha](alpha.md) | Alpha agent. |');
  });

  it('escapes pipes in descriptions to keep the table valid', () => {
    const md = agentsIndexMarkdown([spec('x', 'Has | a pipe inside.')]);
    expect(md).toContain('Has \\| a pipe inside.');
  });

  it('collapses whitespace runs into single spaces', () => {
    const md = agentsIndexMarkdown([spec('x', 'multi\n   line  with  gaps')]);
    expect(md).toContain('multi line with gaps');
  });
});
