import { mkdir, mkdtemp, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { randomBytes, randomUUID } from 'node:crypto';
import { Queue } from 'bullmq';
import { and, asc, eq, sql } from 'drizzle-orm';
import { schema } from '@haive/database';
import {
  configService,
  secretsService,
  userSecretsService,
  logger,
  QUEUE_NAMES,
  TASK_JOB_NAMES,
  type TaskJobPayload,
} from '@haive/shared';
import { initDatabase, getDb } from '../src/db.js';
import { initRedis, getBullRedis, closeRedis } from '../src/redis.js';
import { closeTaskQueue, startTaskWorker } from '../src/queues/task-queue.js';

const log = logger.child({ module: 'onboarding-full-smoke' });

const REQUIRED_ENV = ['DATABASE_URL', 'REDIS_URL', 'CONFIG_ENCRYPTION_KEY'] as const;
for (const k of REQUIRED_ENV) {
  if (!process.env[k]) {
    console.error(`[smoke] missing env ${k}`);
    process.exit(2);
  }
}

interface State {
  fixtureDir?: string;
  userId?: string;
  repoId?: string;
  taskId?: string;
  worker?: Awaited<ReturnType<typeof startTaskWorker>>;
  queue?: Queue<TaskJobPayload>;
}

async function pollUntil<T>(
  fn: () => Promise<T | null>,
  predicate: (val: T) => boolean,
  label: string,
  timeoutMs = 45000,
  intervalMs = 250,
): Promise<T> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const val = await fn();
    if (val !== null && predicate(val)) return val;
    await new Promise((r) => setTimeout(r, intervalMs));
  }
  throw new Error(`timeout waiting for ${label}`);
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}

async function countMarkdownFiles(dir: string, suffix = '.md'): Promise<number> {
  if (!(await pathExists(dir))) return 0;
  try {
    const entries = await readdir(dir, { withFileTypes: true });
    return entries.filter((e) => e.isFile() && e.name.endsWith(suffix)).length;
  } catch {
    return 0;
  }
}

async function countSkillDirs(skillsRoot: string): Promise<number> {
  if (!(await pathExists(skillsRoot))) return 0;
  try {
    const entries = await readdir(skillsRoot, { withFileTypes: true });
    let n = 0;
    for (const e of entries) {
      if (!e.isDirectory()) continue;
      if (await pathExists(path.join(skillsRoot, e.name, 'SKILL.md'))) n += 1;
    }
    return n;
  } catch {
    return 0;
  }
}

async function createFixtureRepo(): Promise<string> {
  const dir = await mkdtemp(path.join(os.tmpdir(), 'haive-onboarding-full-'));
  await writeFile(
    path.join(dir, 'package.json'),
    JSON.stringify(
      {
        name: 'full-smoke-fixture',
        dependencies: { next: '^16.0.0', react: '^19.0.0' },
      },
      null,
      2,
    ),
  );
  await writeFile(
    path.join(dir, 'README.md'),
    '# Full Smoke Fixture\n\nGenerated by onboarding-full-smoke.ts.\n',
  );
  await mkdir(path.join(dir, '__tests__'));
  await writeFile(
    path.join(dir, '__tests__', 'sanity.test.ts'),
    "import { describe, it, expect } from 'vitest';\n\ndescribe('sanity', () => { it('passes', () => { expect(1).toBe(1); }); });\n",
  );
  await mkdir(path.join(dir, 'docs'));
  await writeFile(
    path.join(dir, 'docs', 'architecture.md'),
    '# Architecture\n\nStub docs for smoke.\n',
  );
  return dir;
}

interface RagChunkRow {
  source_path: string;
  chunk_index: number;
}

async function main(): Promise<void> {
  const state: State = {};
  let exitCode = 0;
  try {
    log.info('bootstrapping full onboarding smoke');
    initRedis(process.env.REDIS_URL!);
    await configService.initialize(process.env.REDIS_URL!);
    const db = initDatabase(process.env.DATABASE_URL!);
    await secretsService.initialize(db);
    const masterKek = await secretsService.getMasterKek();
    await userSecretsService.initialize(db, masterKek);

    state.fixtureDir = await createFixtureRepo();
    log.info({ fixture: state.fixtureDir }, 'fixture created');

    const now = new Date();
    const userId = randomUUID();
    state.userId = userId;
    await db.insert(schema.users).values({
      id: userId,
      emailEncrypted: 'onboarding-full-smoke@test.local',
      emailBlindIndex: `onboarding-full-${randomBytes(4).toString('hex')}`,
      passwordHash: 'smoke-not-real',
      role: 'user',
      status: 'active',
      tokenVersion: 0,
      createdAt: now,
      updatedAt: now,
    });

    const [repo] = await db
      .insert(schema.repositories)
      .values({
        userId,
        name: 'full-smoke-fixture',
        source: 'local_path',
        localPath: state.fixtureDir,
        storagePath: state.fixtureDir,
        status: 'ready',
      })
      .returning();
    if (!repo) throw new Error('repo insert failed');
    state.repoId = repo.id;

    const [task] = await db
      .insert(schema.tasks)
      .values({
        userId,
        repositoryId: repo.id,
        type: 'onboarding',
        title: 'onboarding full smoke',
        status: 'created',
        metadata: null,
      })
      .returning();
    if (!task) throw new Error('task insert failed');
    state.taskId = task.id;

    state.worker = startTaskWorker();
    state.queue = new Queue<TaskJobPayload>(QUEUE_NAMES.TASK, {
      connection: getBullRedis(),
    });

    log.info({ taskId: task.id }, 'enqueueing start-task');
    await state.queue.add(TASK_JOB_NAMES.START, { taskId: task.id, userId });

    const formPayloads: Record<string, Record<string, unknown>> = {
      '02-detection-confirmation': {
        projectName: 'full-smoke-fixture',
        framework: 'nextjs',
        primaryLanguage: 'javascript',
        localUrl: 'http://localhost:3000',
        projectDescription: 'Full onboarding smoke covering all 15 steps.',
      },
      '04-tooling-infrastructure': {
        ragMode: 'none',
        ragConnectionString: '',
        mcpEnabled: false,
        lspLanguage: 'typescript',
        installNotes: '',
      },
      '06-workflow-prefs': {
        verificationLevel: 'standard',
        autoCommit: false,
        maxIterations: 5,
        customNotes: 'Generated by onboarding-full-smoke.',
      },
      '06_5-agent-discovery': {
        acceptedAgents: [],
      },
      '07-generate-files': {
        overwrite: true,
      },
      '08-knowledge-acquisition': {
        selectedTopics: ['testing', 'deployment', 'database', 'documentation'],
      },
      '09-qa': {},
      '09_5-skill-generation': {
        selectedSkills: ['testing-skill', 'documentation-skill', 'nextjs-project'],
      },
      '10-rag-populate': {
        truncateExisting: true,
      },
      '11-final-review': {
        acknowledged: true,
        reviewerNotes: 'Full smoke run; template content expected, no CLI.',
      },
      '12-post-onboarding': {
        cleanup: false,
        commit: false,
        commitMessage: '',
      },
    };

    const submitted = new Set<string>();
    let lastStepId: string | null = null;
    let iterations = 0;
    while (iterations < 40) {
      iterations += 1;
      const updated = await pollUntil(
        async () => {
          const row = await db.query.tasks.findFirst({ where: eq(schema.tasks.id, task.id) });
          return row ?? null;
        },
        (t) => {
          if (t.status === 'completed' || t.status === 'failed') return true;
          if (t.status === 'waiting_user' && t.currentStepId !== lastStepId) return true;
          return false;
        },
        `task transition (iter ${iterations})`,
        45000,
      );

      log.info(
        { status: updated.status, currentStepId: updated.currentStepId, iter: iterations },
        'task polled',
      );

      if (updated.status === 'completed') break;
      if (updated.status === 'failed') {
        throw new Error(`task failed: ${updated.errorMessage ?? 'unknown'}`);
      }

      const stepId = updated.currentStepId;
      if (!stepId) throw new Error('waiting_user but no currentStepId');
      if (submitted.has(stepId)) {
        throw new Error(`already submitted ${stepId} but task still waiting`);
      }
      const values = formPayloads[stepId];
      if (!values) throw new Error(`no canned form values for step ${stepId}`);

      log.info({ stepId }, 'submitting form');
      await state.queue.add(TASK_JOB_NAMES.ADVANCE_STEP, {
        taskId: task.id,
        userId,
        stepId,
        formValues: values,
      });
      submitted.add(stepId);
      lastStepId = stepId;
    }

    const finalTask = await db.query.tasks.findFirst({ where: eq(schema.tasks.id, task.id) });
    if (!finalTask) throw new Error('final task vanished');
    if (finalTask.status !== 'completed') {
      throw new Error(`expected completed, got ${finalTask.status}`);
    }

    const allSteps = await db
      .select()
      .from(schema.taskSteps)
      .where(eq(schema.taskSteps.taskId, task.id))
      .orderBy(asc(schema.taskSteps.stepIndex));

    const expected = [
      '01-env-detect',
      '01_5-ripgrep-config',
      '02-detection-confirmation',
      '04-tooling-infrastructure',
      '06-workflow-prefs',
      '06_5-agent-discovery',
      '07-generate-files',
      '07_5-verify-files',
      '08-knowledge-acquisition',
      '09-qa',
      '09_5-skill-generation',
      '09_6-skill-verification',
      '10-rag-populate',
      '11-final-review',
      '12-post-onboarding',
    ];
    for (const id of expected) {
      const row = allSteps.find((s) => s.stepId === id);
      if (!row) throw new Error(`missing step row ${id}`);
      if (row.status !== 'done' && row.status !== 'skipped') {
        throw new Error(`step ${id} status ${row.status}, expected done or skipped`);
      }
    }

    const fixtureDir = state.fixtureDir!;
    const claudeMdPath = path.join(fixtureDir, 'CLAUDE.md');
    if (!(await pathExists(claudeMdPath))) throw new Error('CLAUDE.md missing');
    const claudeMdText = await readFile(claudeMdPath, 'utf8');
    if (!claudeMdText.includes('@AGENTS.md')) {
      throw new Error('CLAUDE.md does not reference @AGENTS.md');
    }

    const agentsMdPath = path.join(fixtureDir, 'AGENTS.md');
    if (!(await pathExists(agentsMdPath))) throw new Error('AGENTS.md missing');

    const agentCount = await countMarkdownFiles(path.join(fixtureDir, '.claude', 'agents'));
    if (agentCount < 10) {
      throw new Error(`expected at least 10 agent files, got ${agentCount}`);
    }
    const commandCount = await countMarkdownFiles(path.join(fixtureDir, '.claude', 'commands'));
    if (commandCount < 3) {
      throw new Error(`expected at least 3 command files, got ${commandCount}`);
    }
    const kbCount = await countMarkdownFiles(path.join(fixtureDir, '.claude', 'knowledge_base'));
    if (kbCount < 3) {
      throw new Error(`expected at least 3 knowledge base files, got ${kbCount}`);
    }
    const skillCount = await countSkillDirs(path.join(fixtureDir, '.claude', 'skills'));
    if (skillCount < 1) {
      throw new Error(`expected at least 1 skill directory with SKILL.md, got ${skillCount}`);
    }
    const workflowConfigPath = path.join(fixtureDir, '.claude', 'workflow-config.json');
    if (!(await pathExists(workflowConfigPath))) {
      throw new Error('.claude/workflow-config.json missing');
    }

    const ragResult = (await db.execute(
      sql`SELECT source_path, chunk_index FROM ai_rag_embeddings WHERE task_id = ${task.id}`,
    )) as unknown;
    const ragRows: RagChunkRow[] = Array.isArray(ragResult) ? (ragResult as RagChunkRow[]) : [];
    if (ragRows.length === 0) {
      throw new Error('ai_rag_embeddings table has no rows for this task');
    }
    const distinctFiles = new Set(ragRows.map((r) => r.source_path)).size;

    const events = await db
      .select()
      .from(schema.taskEvents)
      .where(eq(schema.taskEvents.taskId, task.id));

    log.info(
      {
        steps: allSteps.length,
        agentCount,
        commandCount,
        kbCount,
        skillCount,
        ragChunks: ragRows.length,
        ragDistinctFiles: distinctFiles,
        events: events.length,
      },
      'full smoke assertions passed',
    );

    console.log(
      JSON.stringify({
        smoke: 'ONBOARDING_FULL_OK',
        steps: allSteps.map((s) => ({ stepId: s.stepId, status: s.status })),
        artefacts: {
          agentCount,
          commandCount,
          kbCount,
          skillCount,
          hasClaudeMd: true,
          hasAgentsMd: true,
          hasWorkflowConfig: true,
        },
        rag: {
          rowCount: ragRows.length,
          distinctFiles,
        },
        events: events.length,
      }),
    );
  } catch (err) {
    exitCode = 1;
    log.error({ err }, 'full smoke failed');
    console.error('[full-smoke] FAILED:', err);
  } finally {
    try {
      const db = getDb();
      if (state.taskId) {
        await db
          .execute(sql`DELETE FROM ai_rag_embeddings WHERE task_id = ${state.taskId}`)
          .catch(() => undefined);
        await db.delete(schema.tasks).where(eq(schema.tasks.id, state.taskId));
      }
      if (state.repoId) {
        await db.delete(schema.repositories).where(and(eq(schema.repositories.id, state.repoId)));
      }
      if (state.userId) {
        await db.delete(schema.users).where(eq(schema.users.id, state.userId));
      }
    } catch (cleanupErr) {
      log.warn({ err: cleanupErr }, 'cleanup db rows failed');
    }
    if (state.fixtureDir) {
      await rm(state.fixtureDir, { recursive: true, force: true }).catch(() => {});
    }
    if (state.worker) await state.worker.close().catch(() => {});
    if (state.queue) await state.queue.close().catch(() => {});
    await closeTaskQueue().catch(() => {});
    await closeRedis().catch(() => {});
    process.exit(exitCode);
  }
}

void main();
