import { execFile } from 'node:child_process';
import { chmod, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  commitGeneratedFiles,
  stagedFiles,
} from '../src/step-engine/steps/onboarding/12-post-onboarding.js';

/**
 * The onboarding commit must not let the repository's own hooks rewrite what onboarding just
 * generated.
 *
 * A hook that REWRITES is the case that matters, not one that fails: a failing hook is loud and
 * the step reports it, while a formatter silently changes bytes that `recordOnboardingArtifacts`
 * has already hashed, and every generated file then reads as one Haive did not write. So the
 * fixture below rewrites rather than exiting non-zero.
 */

const exec = promisify(execFile);

const IDENTITY = {
  GIT_AUTHOR_NAME: 'Haive Test',
  GIT_AUTHOR_EMAIL: 'test@haive.local',
  GIT_COMMITTER_NAME: 'Haive Test',
  GIT_COMMITTER_EMAIL: 'test@haive.local',
};

let repo: string;

/** The bytes a generator would have written, and hashed, before the commit runs. */
const GENERATED = '# Agents Index\n\n| Agent | Description |\n';

beforeEach(async () => {
  repo = await mkdtemp(path.join(os.tmpdir(), 'haive-noverify-'));
  await exec('git', ['init', '-q'], { cwd: repo });
  // `core.hooksPath` is left at its default so the hook below is found the way a real repo's
  // would be — this is the mechanism under test, not a stand-in for it.
  await writeFile(path.join(repo, 'AGENTS.md'), GENERATED, 'utf8');

  const hook = path.join(repo, '.git', 'hooks', 'pre-commit');
  await mkdir(path.dirname(hook), { recursive: true });
  // A formatter, in miniature: it rewrites the staged file and re-stages it, which is exactly
  // what prettier-through-lint-staged does and what silently breaks provenance.
  await writeFile(
    hook,
    ['#!/bin/sh', 'printf "REWRITTEN BY HOOK\\n" > AGENTS.md', 'git add AGENTS.md', 'exit 0'].join(
      '\n',
    ),
    'utf8',
  );
  await chmod(hook, 0o755);

  await exec('git', ['add', '-A'], { cwd: repo });
});

afterEach(async () => {
  await rm(repo, { recursive: true, force: true }).catch(() => {});
});

describe('commitGeneratedFiles', () => {
  it('leaves the generated bytes alone when a hook would rewrite them', async () => {
    await commitGeneratedFiles(
      repo,
      'add: agentic workflow setup',
      { ...process.env, ...IDENTITY },
      [],
    );

    // The working tree still holds what onboarding wrote...
    expect(await readFile(path.join(repo, 'AGENTS.md'), 'utf8')).toBe(GENERATED);
    // ...and so does the commit, which is what the artifact row's hash describes.
    const { stdout } = await exec('git', ['show', 'HEAD:AGENTS.md'], { cwd: repo });
    expect(stdout).toBe(GENERATED);
  });

  it('proves the fixture bites — the same hook DOES rewrite an ordinary commit', async () => {
    // Without this the test above passes on a hook that never ran for an unrelated reason (not
    // executable, wrong path, a git version that ignores it), and would keep passing if the flag
    // were dropped. It is the control, not a test of git.
    await exec('git', ['commit', '-m', 'ordinary'], {
      cwd: repo,
      env: { ...process.env, ...IDENTITY },
    });

    expect(await readFile(path.join(repo, 'AGENTS.md'), 'utf8')).toBe('REWRITTEN BY HOOK\n');
  });

  it('runs the hooks when the caller could not isolate the generated files', async () => {
    // The commit is PATHLESS, so it carries the whole index, and `git add` adds to that index
    // rather than replacing it. Where someone else's work is in there too, skipping their checks
    // on their code is the opposite of what the bypass is for — so the caller says no and
    // provenance drift becomes the lesser outcome.
    await commitGeneratedFiles(
      repo,
      'add: agentic workflow setup',
      { ...process.env, ...IDENTITY },
      ['src/theirs.ts'],
    );

    expect(await readFile(path.join(repo, 'AGENTS.md'), 'utf8')).toBe('REWRITTEN BY HOOK\n');
  });
});

describe('stagedFiles', () => {
  it('reports what the index already holds, which is how the caller decides', async () => {
    // Read BEFORE onboarding stages anything: on an existing repository whatever is here is the
    // user's, and it is the only thing that separates "we staged this" from "they did".
    expect(await stagedFiles(repo)).toEqual(['AGENTS.md']);

    await exec('git', ['commit', '--no-verify', '-m', 'base'], {
      cwd: repo,
      env: { ...process.env, ...IDENTITY },
    });
    expect(await stagedFiles(repo)).toEqual([]);
  });
});
